src/hash160.rs, src/hmac.rs, src/lib.rs, src/ripemd160.rs, src/sha1.rs, src/sha256.rs, src/sha256d.rs, src/sha512.rs
Even though the inner value is public for all hash types except `Hmac` it's better to have a well defined common interface for getting the underlying data structure.
I'd propose to make the inner values private to enforce usage of `into_inner(self)`.
=> Implement into_inner for all Hash types

Cargo.toml, src/sha256.rs
This doesn't add support for ripemd or sha256, which we probably
should do at some point, but this is what's required for matching
current rust-lightning/rust-bitcoin fuzztarget support.
=> Add fuzztarget support for sha256

.travis.yml, src/ripemd160.rs, src/sha256.rs, src/sha512.rs
I didn't realize rust-bitcoin had a sha-512 stub. Also include Ripemd-160 stub.
=> Add SHA-512/Ripemd-160 fuzztargets

src/hmac.rs, src/lib.rs, src/ripemd160.rs, src/sha1.rs, src/sha256.rs, src/sha512.rs, src/util.rs
This also adds a block_size to HashEngine, which makes sense since
the engine is really what has the block size, not the hash.
=> Avoid refering to file-specific constants in write_impl macro

.travis.yml
Bumps `rustc` version according to https://github.com/rust-bitcoin/rust-bitcoin/pull/210
=> Bump rustc version to 1.22.0

src/hash160.rs, src/hmac.rs, src/ripemd160.rs, src/serde_macros.rs, src/sha1.rs, src/sha256.rs, src/sha256d.rs, src/sha512.rs
- Modify tests to properly roundtrip for serde (de)serialization.
This blocks https://github.com/rust-bitcoin/rust-bitcoin/pull/215
=> Deserialize into owned String for human-readable deserializer

src/hash160.rs, src/hex.rs, src/hmac.rs, src/lib.rs, src/ripemd160.rs, src/serde_macros.rs, src/sha1.rs, src/sha256.rs, src/sha256d.rs, src/sha512.rs, src/util.rs
Explanation for 7b64c50:
> Since `HashEngine` already has a `block_size` method, and each `Hash` has its corresponding engine under `T::Engine`, we don't need a `block_size` method on `Hash`
=> Use associated constants for LEN and BLOCK_SIZE

CHANGELOG.md, Cargo.toml
After this release, `rust-bitcoin` will be able to successfully integrate with `bitcoin_hashes`.
@apoelstra Please publish to cargo after this gets merged.
=> Bump to 0.3.0 and update CHANGELOG.md

.travis.yml
I didn't actually test if this thing works, but it claims to run the tests and they claim to pass, so at least we can see if things fail to compile with cargo-web in the future. I spent a bit of time fighting with wasm_pack and didn't get anywhere, it appears to require wasm-targeted crates entirely. Given the dependency tree on cargo web and it downloading the emscripten binaries (!) I woulnd't recommend anyone actually use this, but at least its there.
=> Test builds using cargo-web on Travis to ensure they don't break

src/hash160.rs, src/hmac.rs, src/lib.rs, src/ripemd160.rs, src/sha1.rs, src/sha256.rs, src/sha256d.rs, src/sha512.rs
With https://github.com/rust-bitcoin/bitcoin_hashes/pull/14 merged, there is no longer a direct way to construct Hashes from an underlying byte array. This reintroduces a way to do so. This also allows for a more efficient implementation of `impl<D: Decoder> Decodable<D> for sha256d::Hash`.
Needs much discussion because of concerns brought up in https://github.com/rust-bitcoin/bitcoin_hashes/issues/10.
=> [Discussion Needed] Allow constructing Hashes from underlying byte array

src/hex.rs
The check was done on every iteration *and* in the one place where it is constructed in this crate.
=> Enforce even length of HexIterator's underlying str on construction

src/sha256.rs
Builds on https://github.com/rust-bitcoin/bitcoin_hashes/pull/40/.
In Elements we use this type to represent witness merkle roots and Asset IDs.
=> Add sha256::Midstate type

src/hex.rs
Old logic can be _much_ simpler if we make the `HexIterator` wrap a `Char` iterator instead.
=> hex: Simplify and DRY-ify HexIterator

src/lib.rs, src/siphash24.rs
Based on the siphasher crate (https://github.com/jedisct1/rust-siphash/) that is a copy of the implementation in `std::hash`.
=> Add siphash24 module

src/sha1.rs
This makes the behavior of sha1's midstate function in line with everything else, which it should be since it also `write_impl!`s
We should look into how to make our files for individual hashes more DRY using macros or something else, as inconsistencies like this seem to crop up a lot when people forget to modify one file or another and is annoying.
=> sha1: Correct fuzzing behaviour.

src/hex.rs, src/hmac.rs, src/lib.rs, src/ripemd160.rs, src/sha1.rs, src/sha256.rs, src/sha512.rs, src/siphash24.rs
Various cleanups inspired by clippy output. Added sane clippy allows in the last commit. `cargo clippy` should have empty output after this is merged.
=> Repository cleanup w/ help from Clippy

src/sha256.rs
This allows creating const midstates.
Seperate PR from https://github.com/rust-bitcoin/bitcoin_hashes/pull/61 because this change is doesn't need a major version bump and is this compatible with https://github.com/rust-bitcoin/bitcoin_hashes/pull/42.
=> Make sha256::Midstate's inner variable public

src/util.rs
New versions of rust compiler fails to build the crate due to the absent docs for some macros. They also produce some lint warning. This PR fixes the problem.
Sample of the failed build before the fixes applied: https://travis-ci.org/rust-bitcoin/bitcoin_hashes/builds/589871443?utm_source=github_status&utm_medium=notification
UPDATE: Had to roll back some of the linting improvements which were not supported by the current stable rustc version
=> Adding docs to macros and fixeing rust lint warnings

Cargo.toml, src/lib.rs, src/ripemd160.rs, src/sha1.rs, src/sha256.rs, src/sha512.rs, src/siphash24.rs, src/util.rs
Taking an external dependency just to convert ints to byte arrays
is somewhat of a waste, especially when Rust isn't very aggressive
about doing cross-crate LTO.
Note that the latest LLVM pattern-matches this, and while I haven't tested it, that should mean this means no loss of optimization.
=> Drop byteorder dependency (and disable some useless, particularly obnoxious, lints)

src/lib.rs, src/serde_macros.rs, src/util.rs
While I was working on implementing https://github.com/rust-bitcoin/rust-bitcoin/issues/284 I've found that the new `hash_newtype` can't be used outside of `bitcoin_hashes` project due to fact that macros used by it are not exported. This PR fixes the problem for most of such macros.
~~Nevertheless, I am still not able to run https://github.com/pandoracore/rust-bitcoin/blob/hashtypes/src/lib.rs#L67 due to problems with `serde` crate access from inside `hash_newtype` macro. Any suggestions?~~
=> Fixing `hash_newtype` macro to work correctly

src/lib.rs
They were missed due to the last auto merge from the master
=> Adding back crate exports required by hash_newtype macro

Cargo.toml, src/serde_macros.rs
Currently the serde macros (use in creating new hash types) did:
`use hex::ToHex;`
which works fine in this library but not anywhere else.
the only reason it works in `rust-bitcoin` is because it actually used the `hex` crate(https://docs.rs/hex/0.4.0/hex/trait.ToHex.html) without anyone noticing (which was left in non-test code by accident) 
so now it should use the correct hex traits.
=> Make hex path in serde macros relative to the crate

README.md
And remove mention of byteorder dependency.
=> Add MSRV to README

src/lib.rs
Seems to have been an oversight. @apoelstra Let me know if you want me to bump the version right away.
@dr-orlovsky can you review?
=> Implement FromStr for hash newtypes

src/lib.rs, src/sha256t.rs, src/util.rs
Introducing a new `SHA256t` hash type that works as a tagged hash. The idea of tagged hashes is to prevent collisions between hashes meant for different purposes. This type allows tagging these hashes using Rust's type system so that they are semantically different from each other and can't be confused.
It also enables seamless efficient calculation of these hashes.
The `Tag::engine()` method should return a `HashEngine` that is prefilled with data. Of course, it is supposed to have this data statically initialized instead of calculated on call.
Example usage: https://github.com/rust-bitcoin/rust-bitcoin/pull/259
=> Tagged SHA256 hashes

src/lib.rs
Should have been added together with `as_hash`. Just for convenience, I don't need a release for this.
=> Add from_hash to the newtype API

CHANGELOG.md, Cargo.toml, src/lib.rs
We'd like to have a `sha256::Hash` newtype that for some reason we want to be reverse serialized to be compatible with an RPC that parses it reverse.
=> Support hash_newtypes with reversed serialization

src/lib.rs
So FromStr doesn't seem to just refer to FromHex like it should. This fixes that. This bug only manifests for newtypes that have a different hex order than their inner type.
=> Fix FromStr for hash newtypes with custom hex order

.travis.yml, Cargo.toml, src/hash160.rs, src/hmac.rs, src/lib.rs, src/ripemd160.rs, src/sha1.rs, src/sha256.rs, src/sha256d.rs, src/sha256t.rs, src/sha512.rs, src/siphash24.rs
You can already trivially get a slice reference to the inner byte
array for hash types, but its occasionally nice to also be able to
get a direct reference to the inner byte array that isn't through a
fat pointer.
=> Provide an as_inner() for Hash types to get an array reference

src/hmac.rs, src/lib.rs, src/ripemd160.rs, src/sha1.rs, src/sha256.rs, src/sha512.rs, src/siphash24.rs
This is useful for places like:  https://github.com/rust-bitcoin/rust-bitcoin/pull/422
When encoding into a vec we do a sanity assert that the lengths match https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/consensus/encode.rs#L154
this will allow us to do it also when using a hasher.
I'm open to suggestions about the function name because technically not all the bytes were "hashed" yet. but I might be bikeshedding it to much.
=> Add a hashed fn to EngineTrait

README.md
Seems that SHA512 was left out of the list.
=> Add SHA512 to README

src/sha256t.rs
The implementation, present in parent `sha256::Hash` was missed here
=> Implementing FromStr for sha256t::Hash

src/lib.rs
Instead of the default implementation of `Engine::default()`.
This is needed to make newtypes with with `sha256t` tagged hashes for taproot.
=> Implement Hash::engine() for hash newtypes

Cargo.toml, src/hash160.rs, src/hmac.rs, src/lib.rs, src/ripemd160.rs, src/sha1.rs, src/sha256.rs, src/sha256d.rs, src/sha256t.rs, src/sha512.rs, src/siphash24.rs, src/util.rs
This patch adds functionality to optionally be able to generate json schema types.
The generated schemas are not 'complete' verification rules (as they don't know about things like length), but they can be useful for describing an expected return type from e.g. a web client. Future work can add a custom serializer (no great support for declaring this like serde attrs yet) which adds a length validation https://graham.cool/schemars/examples/7-custom_serialization/ and regex to ensure that all fields are hex hashes of appropriate length.
Schemars in particular is a relatively simple library (I've looked it over casually) and has only one new dependency compared to the rust bitcoin crate (dyn-clone).
While this is a WIP, it can be merged. But I'd love to get conceptual feedback here as the …
=> Add Optional JSONSchema Support for Hash Types

src/serde_macros.rs
This slightly improves the serde macro code by moving most of the impl macro code to external traits and wrappers.
This should have no functional change, but it improves the type safety as the SerdeHash trait is declared  in one place, type checked, and monomorphized where needed.
=> Move most of serde trait impl out of macro

CHANGELOG.md, Cargo.toml, src/lib.rs, src/serde_macros.rs
Our last release broke the build for rust-bitcoin iand anything else using the serde impls in this crate) because it moved internals of the serde macros into the non-public `serde_macros` module. This PR exposes the module and bumps the version to fix downstream users.
=> fix serde macro visibility issue, release 0.9.2

CHANGELOG.md, Cargo.toml, src/serde_macros.rs
Still having rust-bitcoin build failures, this time with rustc 1.29.0, due to some module path import rule changes. Cleaned these up a bit; also replaced `std` by `core` everywhere; I don't know if we support serde+no_std but it's good to be consistent.
=> more serde_macro fixes; bump version to 0.9.3

src/hmac.rs
I'm using this to implement a no-std pbkdf2 implementeation for the
bip39 crate.
Should we have an "only use this if you know what you're doing" warning of is that implied?
=> Add Hmac::from_inner_engines constructor

Cargo.toml
The `[dependency.<crate>]` format is not common and is unclear IMO.
=> Reformat the manifest dependency section

src/hash160.rs, src/hmac.rs, src/lib.rs, src/ripemd160.rs, src/sha1.rs, src/sha256.rs, src/sha256d.rs, src/sha256t.rs, src/sha512.rs, src/siphash24.rs
Required in order to make `OutPoint` in rust-bitcoin being `repr(C)`
=> Repr(C) for hash types

Cargo.toml, src/ripemd160.rs, src/sha1.rs, src/sha256.rs, src/sha512.rs, src/siphash24.rs, src/util.rs
https://github.com/rust-bitcoin/rust-secp256k1/pull/264 starts enforcing that 32 bytes of 0s is an invalid private key in fuzzing, which breaks downstream applications which don't bother to check for the sha256-is-broken case. https://github.com/rust-bitcoin/rust-secp256k1/pull/282 keeps that behavior, so best to no longer return 0 hashes from sha256 at all. We also update to use the new fuzzing cfg which is nicer anyway.
=> Use cfg(fuzzing) instead of a fuzztarget feature and don't allow 0-hashes.

src/util.rs
=> use core instead of std in hash_newtype macro

CHANGELOG.md, Cargo.toml, src/lib.rs, src/util.rs
This reverts commit 1b36c27a51e14cb97e592c533045d81e5f257b71.
This broke build of rust-bitcoin. I'm gonna play with it to see if I can get CI to pass without this commit.
=> Revert "don't export core"

.github/workflows/rust.yml, contrib/test.sh, src/lib.rs
There's no reason this should fail to compile.
=> Fix alloc + std builds (and test)

src/impls.rs
For some reason that wasn't implemented yet.
=> Implement `Write` for `HmacEngine`

src/hex.rs
This would allow deserializing objects without allocating the intermediate byte vector like:
```
let tx = Transaction::consensus_decode(HexIterator::new("....").unwrap()).unwrap()
```
Especially useful for libraries like rust_bitcoincore_rpc in places like this https://github.com/rust-bitcoin/rust-bitcoincore-rpc/blob/54a427f2e45b0b8712d44a6995f6a03ad5f961f8/client/src/client.rs#L322-L326
CI is failing on my repo I think for an unrelated reason I am not fully grasping at the moment, @JeremyRubin could you have a look?
=> Implements Read on HexIterator

src/hash160.rs, src/ripemd160.rs, src/sha1.rs, src/sha256.rs, src/sha256d.rs, src/sha256t.rs, src/sha512.rs, src/siphash24.rs, src/util.rs
Since we bumped to Rust 1.29 it has not been necessary to implement `Index` manually, we can get it by way of the `SliceIndex` trait.
Implement `Index` using `SliceIndex`. Keep the declarative macro so we only have to write the `SliceIndex` implementation once.
This is in the same vein as https://github.com/rust-bitcoin/rust-bitcoin/pull/805 but goes about it in a slightly different manner, we should probably be uniform across both crates. I'm unsure which is the best option?
=> Use SliceIndex trait to implement Index

src/hmac.rs
Clippy emits:
warning: redundant slicing of the whole range
As suggested use `key` directly instead of the slice.
=> Remove redundant slicing

fuzz/fuzz_targets/cbor.rs, fuzz/fuzz_targets/json.rs, fuzz/fuzz_targets/ripemd160.rs, fuzz/fuzz_targets/sha1.rs, fuzz/fuzz_targets/sha256.rs, fuzz/fuzz_targets/sha512.rs, src/cmp.rs, src/hash160.rs, src/hex.rs, src/hmac.rs, src/lib.rs, src/ripemd160.rs, src/sha1.rs, src/sha256.rs, src/sha256d.rs, src/sha256t.rs, src/sha512.rs, src/siphash24.rs
Use `rustfmt` to highlight areas in the code that can be cleaned up. All patches are refactor only, no logic changes.
Non-urgent PR.
=> Do manual rustfmt cleanups

Cargo.toml, contrib/test.sh, src/hash160.rs, src/hex.rs, src/hmac.rs, src/ripemd160.rs, src/sha1.rs, src/sha256.rs, src/sha256d.rs, src/sha256t.rs, src/sha512.rs
Improve feature testing by adding all the features to the test matrix and enabling testing with `--no-default-features`.
=> Improve feature coverage in CI test suite

.github/workflows/rust.yml, contrib/test.sh
In order to get access to the `--cfg docsrs` we need to use the nightly
toolchain. Doing so means the CI docs build mirrors the docsrs docs
build so better tests our docs build prior to release.
=> Build docs using nightly toolchain

src/hex.rs, src/hmac.rs, src/lib.rs, src/serde_macros.rs, src/util.rs
After https://github.com/rust-bitcoin/bitcoin_hashes/pull/150 merges we can use the nightly toolchain and get access to the docrs compiler attribute.
Patch 1 and 2 are cleanup in preparation for patch 3 which adds the experimental docrs cfg attribute of form
```
#[cfg_attr(docsrs, doc(cfg(feature = "serde")))]
```
to all non-test code that is feature gated.
=> Use nightly docs features

src/sha256t.rs
When using the `sha256t_hash_newtype` currently no docs are generated,
this causes lint errors for users who lint for such things.
Add docs to the new type created by the `sha256t_hash_newtype` macro.
(This is identical to how we do it in the duplicate macro of the same
name in `rust-bitcoin`, which can be removed in favour of this one after
this patch is applied.)
=> Add docs to the code create by sha256t_hash_newtype macro

.github/workflows/rust.yml, Cargo.toml, README.md, src/cmp.rs, src/hash160.rs, src/hex.rs, src/hmac.rs, src/impls.rs, src/lib.rs, src/ripemd160.rs, src/serde_macros.rs, src/sha1.rs, src/sha256.rs, src/sha256d.rs, src/sha256t.rs, src/sha512.rs, src/siphash24.rs, src/util.rs
Update the MSRV to Rustn 1.41.1 and enable edition 2018.
Should not be merged without rust-bitcoin organization-wide planning on how to go about this upgrade.
Discussion: https://github.com/rust-bitcoin/rust-bitcoin/issues/510#issuecomment-881686342
This one is a bit more involved than the same PRs for [rust-bech32](https://github.com/rust-bitcoin/rust-bech32/pull/57) or [rust-bitcoinconcensus](https://github.com/rust-bitcoin/rust-bitcoinconsensus/pull/34).
The commit message of patch 3:
```
Update to use edition 2018
Add `edition = "2018"` to the minifest file. In order to get the
codebase to build cleanly do:
- Remove usage of `use Hash as HashTrait`, instead use `impl crate::Hash for Hash` and `use Hash as _`.
- Same for HashEngine (remove EngineTrait).
- Add `crate::` to import …
```
=> Enable edition 2018

src/hash160.rs, src/hmac.rs, src/lib.rs, src/ripemd160.rs, src/sha1.rs, src/sha256.rs, src/sha256d.rs, src/sha256t.rs, src/sha512.rs, src/siphash24.rs, src/util.rs
Currently we use `Default::default()` to get an all zeros hash. This is confusing because an all zeroes hash does not have a real meaning since there is no known input to create it. The all zeros hash is, however used by the Bitcoin network to signify certain things (e.g. the previous blockhash in the genesis block).
Remove the `Default` implementation from the `Hash` trait and add a `all_zeros` method instead. Remove the `Default` derive from any hash type that has it.
To see the patch to `rust-bitcoin` that this PR imposes, check out [this branch](https://github.com/tcharding/rust-bitcoin/tree/bitcoin_hashes-all-zeros).
Resolves #139
=> Add all_zeros method to Hash trait

src/cmp.rs, src/lib.rs, src/sha256t.rs, src/util.rs
Leading double colons are a relic of Rust edition 2015, we do not need to use them any more now we are on edition 2018.
=> Remove leading double colons

Cargo.toml
The lib section we have is the same as the defaults, it is unnecessary.
Now that we are using edition 2018 it makes sense to use the more modern
form and not include an explicit lib section.
=> Remove lib section from manifest

src/hex.rs
This struct create an hex string from a writer, in cases where you have
an encodable object this allows skipping the creation of the intermediate `Vec<u8>`
Useful in rust_bitcoin `serialize_hex` https://github.com/rust-bitcoin/rust-bitcoin/blob/0e82376bf85137494ff220608e80b9c78c1932b5/src/consensus/encode.rs#L149 but needs https://github.com/rust-bitcoin/rust-bitcoin/pull/1027 so that result string size is known ahead of time
```
test hex::benches::bench_to_hex                   ... bench:       2,669 ns/iter (+/- 233)
test hex::benches::bench_to_hex_writer            ... bench:       2,034 ns/iter (+/- 167)
```
=> Introduce HexWriter

src/ripemd160.rs, src/sha1.rs, src/sha256.rs, src/sha512.rs, src/util.rs
`rotate_left` is now available in our MSRV: https://doc.rust-lang.org/std/primitive.u32.html#method.rotate_left
=> use rotate_left function instead of macro

CHANGELOG.md
The version has already been bumped. Add release notes in preparation for doing the release.
I mimiced the recent changelog format used in `rust-secp` to do this one. Please do not take me writing these release notes for an implication that I know exactly whats going on :) I just went through ever PR since the last release since there was only on screen worth of them.
This PR could be treated as the release tracking issue.
=> Add v0.11.0 release notes

Cargo.toml, src/lib.rs
The current version of `dyn-clone` v1.0.8 breaks our build (uses `Arc::as_ptr` which only became available in Rust 1.45). 
We can pin the dependency to a version before that works. Requires some toml magic akin to what we do with `actual-serde` in `rust-bitcoin`.
=> Hack around the broken dyn-clone dependency

src/hash160.rs, src/ripemd160.rs, src/sha1.rs, src/sha256.rs, src/sha256d.rs, src/sha256t.rs, src/sha512.rs, src/siphash24.rs, src/util.rs
Patch 2 adds a unit test that can be moved to before patch 1 to verify this PR does what it claims.
From the commit log of patch 1:
`Display` and `LowerHex` offer an 'alternate' option, hex representations by convention should include `0x` if the alternate format is printed.
Currently we implement `Display`, `Debug`, and `LowerHex` all using the same macro. This has two problems, the biggest of which is that we are not correctly handling the alternate format. The second issue is code duplication.
Modify the `impl_hex_fmt` macro to implement `LowerHex` (incl. alternate form), then implement `Display` and `Debug` in the macro making calls to `LowerHex`.
=> Implement `Debug` and `Display` using `LowerHex`

contrib/test.sh
Cargo already uses an env var `RUSTUP_TOOLCHAIN` that controls the
toolchain, no need for our custom `TOOLCHAIN` variable.
=> Remove TOOLCHAIN

src/ripemd160.rs, src/sha1.rs, src/sha256.rs, src/sha512.rs, src/siphash24.rs, src/util.rs
Now that we have Rust > 1.32 we can use methods on stdlib integers to convert to and from little and big endian slices.
- Patch 1: preparatory cleanup
- Patch 2: do the work
- Patch 3: optimisation, use `chunks_exact`
=> Use stdlib integer/slice conversion methods

src/hash160.rs, src/internal_macros.rs, src/lib.rs, src/ripemd160.rs, src/serde_macros.rs, src/sha1.rs, src/sha256.rs, src/sha256d.rs, src/sha256t.rs, src/sha512.rs, src/siphash24.rs
There was a lot of code duplicated for all hash types. Most of it
various standard impls. This made it more tedious and error-prone to
modify the impls for all types.
This commit creates two new macros that take care of implementing the
hash types and calls them from each hash module as needed to keep API
and behavior without a change.
This also extends the `serde_impl!` macro to support generics.
This is preparation for upcoming changes.
=> Deduplicate hash types

.github/workflows/rust.yml, README.md
and run it on nightly only
If it breaks again we'll set it to "allow fail".
=> move schemars to separate CI job

src/sha512.rs
Clippy emits various errors of form:
error: this expression borrows a value the compiler would
automatically borrow
As suggested, remove the unnecessary borrow.
FTR, this error shows up because of a clippy update (I believe).
=> Remove unnecessary borrow

src/error.rs, src/hex.rs, src/impls.rs
Implement `source` for all error types (there are only two). Done because we have bumped the MSRV. First two patches are preparatory cleanup.
=> Update error implementations for the new MSRV

README.md
We are moving this repository to a crate within `rust-bitcoin`, add a section to the readme stating as such.
=> Add comment on repository move/freeze
